# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Forge < Formula
  desc "AI-first quality pipeline for your repo"
  homepage "https://github.com/convergint/forge"
  version "0.5.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/convergint/homebrew-forge/releases/download/v0.5.0/forge_0.5.0_darwin_amd64.tar.gz"
      sha256 "c64c2a59d56828cf5964c05a3cbf1a544a5e1b7c0424c9dab8e8c21a1b8be83a"

      define_method(:install) do
        bin.install "forge"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/convergint/homebrew-forge/releases/download/v0.5.0/forge_0.5.0_darwin_arm64.tar.gz"
      sha256 "20b7a80e9ef2dc6ffa452de62dc20d39b61ced1e29a11bc97ae12d96cd15cf77"

      define_method(:install) do
        bin.install "forge"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/convergint/homebrew-forge/releases/download/v0.5.0/forge_0.5.0_linux_amd64.tar.gz"
      sha256 "8e59043b4c3b48516100497fe1a06b1ebda0e1074b1640f947e0f971854ac126"
      define_method(:install) do
        bin.install "forge"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/convergint/homebrew-forge/releases/download/v0.5.0/forge_0.5.0_linux_arm64.tar.gz"
      sha256 "51370ee3cac955dc1aaf43a8e5b5ae1ed528706c932c9da5b3ae8bc4f461acd4"
      define_method(:install) do
        bin.install "forge"
      end
    end
  end
end
